- name: Playbook to deploy the docker image to Kubernetes
  hosts: webservers
  user: ubuntu
  
  tasks:

  - name: 15. Deploy Successfull Build from DockerHub
    shell:
	  cmd: kubectl set image deployments/coursework-deployment devopscoursework2=kaluber/devopscoursework2:latest
