- name: Playbook for installing Kubectl and Minikube
  hosts: localhost
  user: ubuntu
  vars:
    myPath: /home/ubuntu/
  tasks:

  - name: 1. Update Package Manager
    become: yes
    apt:
      update_cache: yes
  - name: 2. Install apt-transport-https
    become: yes
    apt:
      update_cache: yes
      name: apt-transport-https
  - name: 3. Get APT Key
    shell:
      cmd: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - name: 4. Echo
    shell:
      cmd: echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
  - name: 5. Update Package Manager
    become: yes
    apt:
      update_cache: yes
  - name: 6. Install Kubectl
    become: yes
    apt:
      update_cache: yes
      name: kubectl
  - name: 7. Install Conntrack
    become: yes
    apt:
      update_cache: yes
      name: conntrack
  - name: 8. Download Minikube
    become: yes
    shell:
      cmd: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  - name: 9. Move Minikube
    copy:
      src: minikube
      dest: /usr/local/bin
  - name: 10. Change minikube ownership (executable)
    become: yes
    file:
      path: /usr/local/bin/minikube
      owner: ubuntu
      group: ubuntu
      mode: '777'
  - name: 11. Start Minikube
    shell:
      cmd: minikube start

